Description: Common support SNS Topics for AWS development
Parameters:
  ScriptFolder:
    Description: Folder that contains the python and sql scripts referenced by this data pipeline.
    Type: String
  FeedName:
    Description: Name of the feed to upload
    Type: String
  LogFolder:
    Description: S3 Location for the Data Pipeline to log to
    Type: String
  AMIImageId:
    Description: EC2 Image to use
    Type: String
  EC2InstanceType:
    Description: EC2 Instance Type
    Type: String
  EC2KeyPair:
    Description: KeyPair to use to access the EC2 instance
    Type: String
Resources:
  FileIngestionUploadToS3:
    Type: "AWS::DataPipeline::Pipeline"
    Properties:
      Name:
        Fn::Sub:
        - "FileIngestionUploadToS3_${FeedName}"
        - FeedName:
            Ref: FeedName
      Description:
        Fn::Sub:
        - "Pipeline to download the ${FeedName} feed and upload it to S3"
        - FeedName:
            Ref: FeedName
      Activate: false
      ParameterObjects:
        - Id: "myDataPipeLineLogFolder"
          Attributes:
            - Key: "description"
              StringValue: "S3 folder that the Data Pipeline logs to"
            - Key: "type"
              StringValue: "String"
            - Key: "default"
              StringValue: "s3://aws-logs-019672110497-us-east-1/datapipeline"
        - Id: "myInputScriptsFolder"
          Attributes:
            - Key: "description"
              StringValue: "S3 folder that the Data Pipeline logs to"
            - Key: "type"
              StringValue: "String"
            - Key: "default"
              StringValue: "s3://aws-logs-019672110497-us-east-1/datapipeline"
        - Id: "myAMIImageId"
          Attributes:
            - Key: "description"
              StringValue: "EC2 Image to use"
            - Key: "type"
              StringValue: "String"
            - Key: "default"
              StringValue: "ami-67cf2a19"
        - Id: "myEC2InstanceType"
          Attributes:
            - Key: "description"
              StringValue: "EC2 Type"
            - Key: "type"
              StringValue: "String"
            - Key: "default"
              StringValue: "t2.micro"
        - Id: "myEC2KeyPair"
          Attributes:
            - Key: "description"
              StringValue: "KeyPair to use to be able to access the EC2 instance"
            - Key: "type"
              StringValue: "String"
            - Key: "default"
              StringValue: "EC2First"
      ParameterValues:
        - Id: "myDataPipeLineLogFolder"
          StringValue:
            Ref: LogFolder
        - Id: "myInputScriptsFolder"
          StringValue:
            Ref: ScriptFolder
        - Id: "myAMIImageId"
          StringValue:
            Ref: AMIImageId
        - Id: "myEC2InstanceType"
          StringValue:
            Ref: EC2InstanceType
        - Id: "myEC2KeyPair"
          StringValue:
            Ref: EC2KeyPair
      PipelineObjects:
        - Id: "Default"
          Name: "Default"
          Fields:
            - Key: "type"
              StringValue: "Default"
            - Key: "scheduleType"
              StringValue: "ONDEMAND"
            - Key: "failureAndRerunMode"
              StringValue: "CASCADE"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "resourceRole"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloperResource
            - Key: "pipelineLogUri"
              StringValue: "#{myDataPipeLineLogFolder}"
        - Id: "InputScriptsFolderDataNode"
          Name: "InputScriptsFolderDataNode"
          Fields:
            - Key: "type"
              StringValue: "S3DataNode"
            - Key: "directoryPath"
              StringValue: "#{myInputScriptsFolder}"
        - Id: Runner
          Name: "Runner"
          Fields:
            - Key: "type"
              StringValue: "Ec2Resource"
            - Key: "imageId"
              StringValue: "#{myAMIImageId}"
            - Key: "instanceType"
              StringValue: "#{myEC2InstanceType}"
            - Key: "keyPair"
              StringValue: "#{myEC2KeyPair}"
            - Key: "terminateAfter"
              StringValue: "4 HOURS"
        - Id: ShellActivity
          Name: "ShellScript"
          Fields:
            - Key: "type"
              StringValue: "ShellCommandActivity"
            - Key: "input"
              RefValue: InputScriptsFolderDataNode
            - Key: "scriptUri"
              StringValue: "#{myInputScriptsFolder}/hmda_ingestion.sh"
            - Key: "stage"
              StringValue: "true"
            - Key: "maximumRetries"
              StringValue: "0"
            - Key: "runsOn"
              RefValue: Runner
            - Key: "onFail"
              RefValue: FailureEmail
            - Key: "onFail"
              RefValue: FailureLogging
            - Key: "onSuccess"
              RefValue: KickOffPipeline
            - Key: "onSuccess"
              RefValue: SuccessEmail
            - Key: "onSuccess"
              RefValue: SuccessfulLogging
        - Id: KickOffPipeline
          Name: "KickOffPipeline"
          Fields:
            - Key: "type"
              StringValue: "SnsAlarm"
            - Key: "message"
              StringValue: "{ 'pipeline_id': 'df-0230793SAN246TOW009' }"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "subject"
              StringValue: "Kick off Orc Conversion"
            - Key: "topicArn"
              StringValue:
                Fn::ImportValue: ActivateDataPipelineTopic
        - Id: SuccessEmail
          Name: "SuccessEmail"
          Fields:
            - Key: "type"
              StringValue: "SnsAlarm"
            - Key: "message"
              StringValue: "Data Upload Succeeded"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "subject"
              StringValue: "Data Upload Succeeded"
            - Key: "topicArn"
              StringValue:
                Fn::ImportValue: ETLAdminEmailSubscriptionTopic
        - Id: FailureEmail
          Name: "FailureEmail"
          Fields:
            - Key: "type"
              StringValue: "SnsAlarm"
            - Key: "message"
              StringValue: "Data Ingestion Failed; Please check the logs"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "subject"
              StringValue: "Data Ingestion Failed"
            - Key: "topicArn"
              StringValue:
                Fn::ImportValue: ETLAdminEmailSubscriptionTopic
        - Id: SuccessfulLogging
          Name: "SuccessfulLogging"
          Fields:
            - Key: "type"
              StringValue: "SnsAlarm"
            - Key: "message"
              StringValue: "{ 'message': 'The HMDA upload ingestion process was successful.', 'priority': 'info' }"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "subject"
              StringValue: "Data Upload Succeeded"
            - Key: "topicArn"
              StringValue:
                Fn::ImportValue: CloudWatchLogTopic
        - Id: FailureLogging
          Name: "FailureLogging"
          Fields:
            - Key: "type"
              StringValue: "SnsAlarm"
            - Key: "message"
              StringValue: "{ 'message': 'The Data Upload Process had an error.  Please check the Data Pipeline logs.', 'priority': 'error' }"
            - Key: "role"
              StringValue:
                Fn::ImportValue: DataPipelineDeveloper
            - Key: "subject"
              StringValue: "Failure in Data Download and Ingestion"
            - Key: "topicArn"
              StringValue:
                Fn::ImportValue: CloudWatchLogTopic
