Description: Creating permmissions for the support Lambda functions
Resources:
  LambdaCloudWatchLogsAndDataPipeline:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: LambdaCloudWatchLogsAndDataPipeline
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSDataPipeline_FullAccess
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "lambda.amazonaws.com"
            Action:
            - "sts:AssumeRole"
  LambdaCloudWatchLogs:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: LambdaCloudWatchLogs
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "lambda.amazonaws.com"
            Action:
            - "sts:AssumeRole"
  DataPipelineDeveloper:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DataPipelineDeveloper
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSDataPipelineRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "elasticmapreduce.amazonaws.com"
              - "datapipeline.amazonaws.com"
            Action:
            - "sts:AssumeRole"
  DataPipelineDeveloperResource:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DataPipelineDeveloperResource
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforDataPipelineRole
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "ec2.amazonaws.com"
            Action:
            - "sts:AssumeRole"

Outputs:
  LambdaCloudWatchLogsAndDataPipeline:
    Description: IAM Role for Lambda Function that needs access to CloudWatch Logs and Data Pipeline
    Export:
      Name: LambdaCloudWatchLogsAndDataPipeline
    Value:
      Fn::GetAtt:
      - LambdaCloudWatchLogsAndDataPipeline
      - Arn
  LambdaCloudWatchLogs:
    Description: IAM Role for Lambda Function that needs access to CloudWatch Logs
    Export:
      Name: LambdaCloudWatchLogs
    Value:
      Fn::GetAtt:
      - LambdaCloudWatchLogs
      - Arn
  DataPipelineDeveloper:
    Description: IAM Role for Data Pipeline Runner
    Export:
      Name: DataPipelineDeveloper
    Value:
      Fn::GetAtt:
      - DataPipelineDeveloper
      - Arn
  DataPipelineDeveloperResource:
    Description: IAM Role for Data Pipeline Resource Runner
    Export:
      Name: DataPipelineDeveloperResource
    Value:
      Fn::GetAtt:
      - DataPipelineDeveloperResource
      - Arn
