Description: Common support SNS Topics for AWS development

Resources:
  ETLAdminEmailSubscriptionTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ETLAdminEmailSubscriptionTopic
Outputs:
  ETLAdminEmailSubscriptionTopic:
    Description: IAM Role for Lambda Function that needs access to CloudWatch Logs and Data Pipeline
    Export:
      Name: ETLAdminEmailSubscriptionTopic
    Value:
      Ref: ETLAdminEmailSubscriptionTopic
